### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by bramus** [mfrachet/rn-bridge-monitor#5]
Hi, I'm testing this out with an RN 0.52 app. Having followed the installation and using the example code from the README, I see stuff appear in the Monitor, but only when running my app in the iOS Simulator.

When running it in the Android Emulator nothing happens. Are there extra steps that one needs to perform in order to get it working with Android? The virtual device is running Android 7.1.1.

**Comment by mfrachet** [comment]
I think that you can run it using https://github.com/mfrachet/rn-bridge-monitor/blob/master/docs/INSIDE.md#choosing-the-server-location-from-the-react-native-application :)

**Comment by bramus** [comment]
Thanks @mfrachet. For Android I indeed had to explicitly set the server to write to.
